# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d71b3c02e2a924b03a1f30a3fbf22c07680c63e981a06798b703de3a1d9b403665ab8b36a3d45077b5ab2f9445bd637534d451a70c3de9b32403623c50897a8d
  
test:
  secret_key_base: 488030ae1062996b79c40177ac1fb6c526da07456c6af7403e170faa753e732848f479e6e714be6d2787a98ade845a9ae206f67f80d27fe4c1fe2b2f1ba50e83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  google_analytics_code: YOUR CODE HERE
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

